name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: classic
          base: header, activity, community, repositories, metadata
          token: ${{ secrets.METRICS_TOKEN }}
          # Enable the isometric calendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_traffic: yes
          # Wakatime integration
          plugin_wakatime: yes
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_languages_ignored: markdown, plaintext, text, xml, yaml, JSON
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          # Steam integration
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561197960287930"
          # Starlist
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 14
          plugin_starlists_limit_repositories: 20
          plugin_starlists_only: Awesome
          # Plugin Languages
          plugin_languages: yes
          plugin_languages_colors: rainbow
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 14
          plugin_languages_analysis_timeout: 15
