name: Metrics

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@latest
        with:
          template: classic
          base: header, activity, community, repositories, metadata
          token: ${{ secrets.METRICS_TOKEN }}
          repositories: 100
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_traffic: yes
          plugin_wakatime: yes
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_languages_ignored: markdown, plaintext, text, xml, yaml, JSON
          plugin_wakatime_days: 365
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561198846755720"
          plugin_languages: yes
          plugin_languages_colors: rainbow
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 14
          plugin_languages_analysis_timeout: 15
